config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 512}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: {minimum: 3, maximum: 15}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }, length: { maximum: 105 }
  
  has_many :articles, dependent: :destroy

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform this action!"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_or_admin_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end
  
  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_or_admin_user
    if (current_user != @article.user && !current_user.admin?)
      flash[:alert] = "You are not authorized to perform this action!"
      redirect_to article_path(@article)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category #{@category.name} is created."
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category #{@category.name} updated successfully."
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[alert] = "You are not authorized to perform this action."
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.username}!"
      redirect_to articles_path
    else
      flash.now[:alert] = "Your email and password do not match"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_same_user_or_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end
  
  def update
    if (@user.update(user_params))
      flash[:notice] = "Your profile is updated successfully."
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if (@user.save)
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Alpha Blog! You have successfully signed up."
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil if current_user == @user
    @user.destroy
    flash[:notice] = "Account and all associated articles deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if (current_user != @user)
      flash[:alert] = "You are not authorized to perform this action!"
      redirect_to user_path(@user)
    end
  end

  def require_same_user_or_admin
    if (current_user != @user && !current_user.admin?)
      flash[:alert] = "You are not authorized to perform this action!"
      redirect_to user_path(@user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, size = 64)
    email_address = user.email.downcase
    hash = hash = Digest::MD5.hexdigest(email_address)
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: "#{user.username}'s profile picture", class: "rounded mx-auto d-block shadow")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<% articles.each do |article| %>
  <div class="row justify-content-md-center">
    <div class="container my-4 col-7">
      <div class="card text-center shadow bg-dark text-light">
        <div class="card-header font-italic">
          By <%= link_to article.user.username, user_path(article.user) %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "article-title" %></h5>
          <% article.categories.each do |category| %>
            <%= link_to category.name, category_path(category), class: "card-title badge badge-pill badge-primary" %>
          <% end %>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
          <%= link_to "View", article_path(article), class: "btn btn-primary mx-1" %>
          <% if logged_in? && (article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-success mx-1" %>
            <%= link_to "Delete", article_path(article), class: "btn btn-danger mx-1", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class="row">
  <div class="container col-8">
    <%= render 'shared/error', obj: @article %>
    <%= form_with(model: @article, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "Article title", required: "true" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", rows: "7", placeholder: "Article description (max 512 characters)", required: "true" %>
      </div>
      <div class="form-group">
        <%= f.label :category %>
        <%= collection_select(:article, :category_ids, Category.all, :id, :name, { prompt: "Choose categories (Optional)" }, { multiple: true, class: "form-control col-4" }) %>
      </div>
      <%= f.submit class: "btn btn-outline-primary mr-2 d-inline-block" %>
      <%= link_to 'Cancel', articles_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="heading text-center mt-3 display-4">Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="heading text-center mt-3 display-4">Articles</h1>

<% if logged_in? %>
  <div class="row justify-content-center">
    <%= link_to 'Create new article', new_article_path, class: "btn-custom my-3 justify-content-md-center" %>
  </div>
<% end %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles', articles: @articles %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<% if logged_in? %>
  <div class="row justify-content-center">
    <%= link_to 'Create new article', new_article_path, class: "btn-custom my-3 justify-content-md-center" %>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1 class="heading text-center mt-3 display-4">New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="heading text-center mt-3 display-4"><%= @article.title %></h1>
<div class="row justify-content-md-center">
  <div class="container my-4 col-7">
    <div class="card text-center shadow bg-dark text-light">
      <div class="card-header font-italic">
        By <%= link_to @article.user.username, user_path(@article.user) %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= link_to @article.title, article_path(@article), class: "article-title" %></h5>
        <% @article.categories.each do |category| %>
          <%= link_to category.name, category_path(category), class: "card-title badge badge-pill badge-primary" %>
        <% end %>
        <p class="card-text text-left"><%= @article.description %></p>
      </div>
      <div class="card-footer text-muted">
        Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago
      </div>
    </div>
  </div>
</div>
<div class="row justify-content-center">
  <%= link_to 'Return to articles listing', articles_path, class: "btn-custom mb-4" %>
</div>

app/views/categories/_form.html.erb
<div class="row">
  <div class="container col-6">
    <%= render 'shared/error', obj: @category %>
    <%= form_with(model: @category, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :name, "Category Name" %>
        <%= f.text_field :name, class: "form-control", placeholder: "Choose a name", required: "true" %>
      </div>
      <%= f.submit  class: "btn btn-outline-primary mr-2 d-inline-block" %>
      <%= link_to 'Cancel', categories_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="heading text-center mt-3 display-4">Edit Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="heading text-center mt-3 display-4">Categories</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<% @categories.each do |category| %>
  <div class="row justify-content-md-center">
    <div class="container my-4 col-4">
      <div class="card text-center shadow bg-dark text-light">
        <div class="card-header font-italic">
          <h5 class="card-title"><%= link_to category.name, category_path(category) %></h5>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to image_tag(category.image, alt: "#{category.name}", class: "rounded mx-auto mb-4 d-block shadow w-25"), category_path(category) %></h5>
          <%= link_to "View", category_path(category), class: "btn btn-primary mx-1" %>
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Edit", edit_category_path(category), class: "btn btn-success mx-1" %>
            <%= link_to "Delete", category_path(category), class: "btn btn-danger mx-1", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="card-footer">
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="heading text-center mt-3 display-4">Create New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="heading text-center mt-3 display-4">Category <%= @category.name %></h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/articles', articles: @articles %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, class: ["alert", "alert-#{name == "notice" ? "success" : "danger"}", "alert-dismissible", "fade", "show"], role: "alert" do %>
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark shadow">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "View Articles", articles_path, class: "dropdown-item" %>
          <%= link_to "Write Article", new_article_path, class: "dropdown-item" if logged_in? %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Categories", categories_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light font-weight-bold" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username %> <%= "(Admin)" if current_user.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", logout_path, class: "dropdown-item", method: :delete %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link text-light font-weight-bold" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>
<%= link_to 'Articles listing', articles_path %>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<section class="section-home" id="page-content">
  <div class="container home-container text-center text-light">
    <div class="jumbotron my-auto mx-auto">
      <h1 class="display-4">Wecome to Alpha Blog!</h1>
      <p class="lead">Blogging website that let's you speak your mind.</p>
      <hr class="my-4 bg-light w-75">
      <p>What are you waiting for? Sign up now to post your Alpha Blog!</p>
      <%= link_to 'Sign up', signup_path, class: "btn btn-primary btn-lg mt-4" %>
    </div>
  </div>
</section>

<footer id="sticky-footer" class="py-3 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h2>The following errors prevented the <%= obj.class.name.downcase %> from being saved</h2>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="row">
  <div class="container col-6">
    <%= render 'shared/error', obj: @user %>
    <%= form_with(model: @user, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control", placeholder: "Enter your email", required: "true" %>
      </div>
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control", placeholder: "Choose a username", required: "true" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control", placeholder: "Choose a password", required: "true" %>
      </div>
      <%= f.submit(@user.new_record? ? "Sign up" : "Update", class: "btn btn-outline-primary mr-2 d-inline-block") %>
      <%= link_to 'Cancel', @user.new_record? ? root_path : user_path(@user), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="heading text-center mt-3 display-4">Edit Your Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="heading text-center mt-3 display-4">Alpha Bloggers</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<% @users.each do |user| %>
  <div class="row justify-content-md-center">
    <div class="container my-4 col-7">
      <div class="card text-center shadow bg-dark text-light">
        <div class="card-header font-italic">
          <%= link_to user.username, user_path(user) %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to gravatar_for(user, 150), user_path(user) %></h5>
          <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
          <%= link_to "View Profile", user_path(user), class: "btn btn-primary" %>
        </div>
        <div class="card-footer text-muted">
          Joined <%= time_ago_in_words(user.created_at) %> ago
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="heading text-center mt-3 display-4">Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="heading text-center mt-3 display-4"><%= @user.username %></h1>
<%= gravatar_for(@user, 200) %>

<% if logged_in? && @user == current_user %>
  <div class="row justify-content-center">
    <%= link_to "Edit Profile", edit_user_path(@user), class: "btn-lg btn-outline-primary mt-4" %>
  </div>
<% end %>
<% if logged_in? && (@user == current_user || current_user.admin?) %>
<div class="row justify-content-center">
  <%= link_to "Delete Account", user_path(@user), class: "btn btn-outline-danger mt-4", method: :delete, data: {confirm: "Are you sure? (All your articles will also be deleted)"} %>
</div>
<% end %>

<h2 class="text-center mt-3 display-4">Articles</h2>

<% if logged_in? %>
  <div class="row justify-content-center">
    <%= link_to 'Create new article', new_article_path, class: "btn-custom my-3 justify-content-md-center" %>
  </div>
<% end %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/articles', articles: @articles %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<% if logged_in? && @user.articles.count > 0 %>
  <div class="row justify-content-center">
    <%= link_to 'Create new article', new_article_path, class: "btn-custom my-3 justify-content-md-center" %>
  </div>
<% end %>